<?php


// So far I was just testing the capabilities for certain field groups to be added only for certain users. 
// This could perhaps allow admins to easily add tailwind classes or other utility classes to blocks while
// not giving all user the same capbalities. Not sure if we will do this, but there could be other uses as well.  

add_action('acf/include_fields', function () {
    return; // Disable for now
    if (! current_user_can('administrator')) {
        return;
    }
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
        'key' => 'group_66ef8c5d0acab',
        'title' => 'Style Builder',
        'fields' => array(
            array(
                'key' => 'field_66ef8e2696f87',
                'label' => 'Style Builder',
                'name' => '',
                'aria-label' => '',
                'type' => 'accordion',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_66ef8c5d59c59',
                'label' => 'Style Builder',
                'name' => 'style_builder',
                'aria-label' => '',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_66f1e6fbff932' => array(
                        'key' => 'layout_66f1e6fbff932',
                        'name' => 'class_list',
                        'label' => 'Class List',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66f1e703ff934',
                                'label' => 'Class List',
                                'name' => 'class_list',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'rows' => '',
                                'placeholder' => '',
                                'new_lines' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66ef8c81decfc' => array(
                        'key' => 'layout_66ef8c81decfc',
                        'name' => 'spacing',
                        'label' => 'Spacing',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66ef8d85b824f',
                                'label' => 'Spacing Type',
                                'name' => 'spacing_type',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'Margin' => 'Margin',
                                    'Padding' => 'Padding',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef8ca3b824d',
                                'label' => 'Sides',
                                'name' => 'spacing_side',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    't' => 'Top',
                                    'b' => 'Bottom',
                                    'l' => 'Left',
                                    'r' => 'Right',
                                ),
                                'default_value' => array(),
                                'return_format' => 'value',
                                'multiple' => 1,
                                'allow_null' => 0,
                                'allow_in_bindings' => 1,
                                'ui' => 1,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef8d1bb824e',
                                'label' => 'Spacing Amount',
                                'name' => 'spacing_options',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    20 => '20',
                                    30 => '30',
                                    40 => '40',
                                    50 => '50',
                                    60 => '60',
                                    70 => '70',
                                    80 => '80',
                                    'block' => 'Block',
                                    'custom' => 'Custom',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef8f19a38b2',
                                'label' => 'Custom',
                                'name' => 'spacing_custom',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => 'Custom option requires units (px,rem,em,vw,clamp,etc)',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef8d1bb824e',
                                            'operator' => '==',
                                            'value' => 'custom',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66ef91c3aa504' => array(
                        'key' => 'layout_66ef91c3aa504',
                        'name' => 'colors',
                        'label' => 'Colors',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66ef91d6aa506',
                                'label' => 'Text Color',
                                'name' => 'text_color',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'base' => 'Base',
                                    'contrast' => 'Contrast',
                                    'primary' => 'Primary',
                                    'secondary' => 'Secondary',
                                    'tertiary' => 'Tertiary',
                                    'neutral' => 'Neutral',
                                    'alert' => 'Alert',
                                    'custom' => 'Custom',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef94ebbf377',
                                'label' => 'Text Custom',
                                'name' => 'text_custom',
                                'aria-label' => '',
                                'type' => 'color_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef91d6aa506',
                                            'operator' => '==',
                                            'value' => 'custom',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'enable_opacity' => 0,
                                'return_format' => 'string',
                                'allow_in_bindings' => 0,
                            ),
                            array(
                                'key' => 'field_66ef91e0aa507',
                                'label' => 'Background Color',
                                'name' => 'background_color',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'base' => 'Base',
                                    'contrast' => 'Contrast',
                                    'primary' => 'Primary',
                                    'secondary' => 'Secondary',
                                    'tertiary' => 'Tertiary',
                                    'neutral' => 'Neutral',
                                    'alert' => 'Alert',
                                    'custom' => 'Custom',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef94ffbf378',
                                'label' => 'Background Custom',
                                'name' => 'background_custom',
                                'aria-label' => '',
                                'type' => 'color_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef91e0aa507',
                                            'operator' => '==',
                                            'value' => 'custom',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'enable_opacity' => 0,
                                'return_format' => 'string',
                                'allow_in_bindings' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66ef95d0b1a70' => array(
                        'key' => 'layout_66ef95d0b1a70',
                        'name' => 'positioning',
                        'label' => 'Positioning',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66ef95dab1a72',
                                'label' => 'Positioning Type',
                                'name' => 'positioning_type',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'static' => 'Static',
                                    'relative' => 'Relative',
                                    'absolute' => 'Absolute',
                                    'fixed' => 'Fixed',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef95fdb1a73',
                                'label' => 'Top',
                                'name' => 'top',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef95dab1a72',
                                            'operator' => '!=',
                                            'value' => 'static',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66ef964cb1a74',
                                'label' => 'Left',
                                'name' => 'left',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef95dab1a72',
                                            'operator' => '!=',
                                            'value' => 'static',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66ef9650b1a75',
                                'label' => 'Bottom',
                                'name' => 'bottom',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef95dab1a72',
                                            'operator' => '!=',
                                            'value' => 'static',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66ef9653b1a76',
                                'label' => 'Right',
                                'name' => 'right',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef95dab1a72',
                                            'operator' => '!=',
                                            'value' => 'static',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66ef9855e45c9' => array(
                        'key' => 'layout_66ef9855e45c9',
                        'name' => 'display',
                        'label' => 'Display',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66ef985de45cb',
                                'label' => 'Display',
                                'name' => 'display',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'block' => 'Block',
                                    'inline' => 'Inline',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_66ef997010864' => array(
                        'key' => 'layout_66ef997010864',
                        'name' => 'typography',
                        'label' => 'Typography',
                        'display' => 'row',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_66ef99c710866',
                                'label' => 'Font Family',
                                'name' => 'font_family',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'secondary' => 'Inter',
                                    'primary' => 'Saira',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef99db10867',
                                'label' => 'Font Size',
                                'name' => 'font_size',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'sm' => 'Small',
                                    'md' => 'Medium',
                                    'lg' => 'Large',
                                    'xl' => 'xLarge',
                                    'two-x-lg' => '2xLarge',
                                    'three-x-lg' => '3xLarge',
                                    'four-x-lg' => '4xLarge',
                                    'five-x-lg' => 'fivexlarge',
                                    'hero' => 'Hero',
                                    'custom' => 'Custom',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef9a98974bb',
                                'label' => 'Font Size Custom',
                                'name' => 'font_size_custom',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef99db10867',
                                            'operator' => '==',
                                            'value' => 'custom',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_66ef99ec10868',
                                'label' => 'Font Weight',
                                'name' => 'font_weight',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'thin' => 100,
                                    'semi-bold' => 600,
                                    'regular' => 400,
                                    'medium' => 500,
                                    'light' => 300,
                                    'extra-light' => 200,
                                    'extra-bold' => 800,
                                    'bold' => 700,
                                    'black' => 900,
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 1,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef99fc10869',
                                'label' => 'Font Case',
                                'name' => 'font_case',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'uppercase' => 'Uppercase',
                                    'lowercase' => 'Lowercase',
                                    'capitalize' => 'Capitalize',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef9a301086a',
                                'label' => 'Line Height',
                                'name' => 'line_height',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'default' => 'Default',
                                    'large' => 1.75,
                                    'medium' => 1.5,
                                    'small' => 1.25,
                                    'x-large' => 2,
                                    'x-small' => 1.1000000000000001,
                                    'custom' => 'Custom',
                                ),
                                'default_value' => false,
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'allow_in_bindings' => 1,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_66ef9a8d974ba',
                                'label' => 'Line Height Custom',
                                'name' => 'line_height_custom',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_66ef9a301086a',
                                            'operator' => '==',
                                            'value' => 'custom',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'allow_in_bindings' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'min' => '',
                'max' => '',
                'button_label' => 'Add Rule',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/nkg-group',
                ),
            ),
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/nkg-textarea',
                ),
            ),
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/nkg-image',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});
